all:
	make -C a1
	make -C a2
	make -C a3
	make -C straights

test:
	make -C a1 test
	make -C a2 test
	make -C a3 test
	make -C straights test


clean:
	make -C a1 clean
	make -C a2 clean
	make -C a3 clean
	make -C straights clean
